### ISSUE TITLE
Can someone provide magnet link to 30B model please?

### ISSUE THREAD

**Issue by thedmdim** [antimatter15/alpaca.cpp#120]
I cannot download from _huggingface_ cause the size is too big and condition speed is too slow

**Comment by Castaa** [comment]
there has to be a torrent of alpaca 30B and 65B.  I search google for it everyday but nothing has surfaced just yet.

**Comment by erhathaway** [comment]
On, linux:

`wget https://huggingface.co/Pi3141/alpaca-30B-ggml/resolve/main/ggml-model-q4_0.bin -O ggml-model-q4_0.bin`

**Comment by Castaa** [comment]
try this magnet for 30B
`
magnet:?xt=urn:btih:6K5O4J7DCKAMMMAJHWXQU72OYFXPZQJG&dn=ggml-alpaca-30b-q4.bin&xl=20333638921&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce`

**Comment by Castaa** [comment]
`magnet:?xt=urn:btih:6K5O4J7DCKAMMMAJHWXQU72OYFXPZQJG&dn=ggml-alpaca-30b-q4.bin&xl=20333638921&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce`

I hope this magnet link works properly. I've never created one before This the alpaca.cpp 30B 4-bit weight file.  Same file downloaded form huggingface.  Let me know if it doesn't work.   Apologies if it doesn't.

**Comment by mallory303** [comment]
Unfortunately I have problems with it
Anybody has idea what is the problem?

llama_model_load: loading model from 'ggml-model-q4_0.bin' - please wait ...
llama_model_load: ggml ctx size = 25631.50 MB
llama_model_load: memory_size =  6240.00 MB, n_mem = 122880
llama_model_load: loading model part 1/4 from 'ggml-model-q4_0.bin'
llama_model_load: llama_model_load: tensor 'tok_embeddings.weight' has wrong size in model file
main: failed to load model from 'ggml-model-q4_0.bin'

**Comment by mallory303** [comment]
It's works now, thanks :)
