### ISSUE TITLE
main: failed to load model from 'alpaca-30B-ggml/ggml-model-q4_0.bin'

### ISSUE THREAD

**Issue by nasirus** [antimatter15/alpaca.cpp#121]
I have an issue with using the alpaca-30B-ggml model. I downloaded the repo source with:

git clone https://huggingface.co/Pi3141/alpaca-30B-ggml

Then I executed the script:

./chat -m alpaca-30B-ggml/ggml-model-q4_0.bin

I myself built the solution with:

git clone https://github.com/antimatter15/alpaca.cpp
cd alpaca.cpp

make chat

here is the error message:

main: seed = 1679496066
llama_model_load: loading model from 'alpaca-30B-ggml/ggml-model-q4_0.bin' - please wait ...
llama_model_load: invalid model file 'alpaca-30B-ggml/ggml-model-q4_0.bin' (bad magic)
main: failed to load model from 'alpaca-30B-ggml/ggml-model-q4_0.bin'

**Comment by cesarandreslopez** [comment]
@nasirus make sure you have git-lfs installed.

in ubuntu:

```
sudo apt-get install git-lfs
```

**Comment by TheStranjer** [comment]
Tried that. @cesarandreslopez Same error.

**Comment by nasirus** [comment]
> @nasirus make sure you have git-lfs installed.
> 
> in ubuntu:
> 
> ```
> sudo apt-get install git-lfs
> ```

@cesarandreslopez thank you for your answer, it works perfectly

@TheStranjer 
try do delete repository first : 
sudo rm -r alpaca-30B-ggml 
install git-lfs:
sudo apt-get install git-lfs
download it again :
git clone https://huggingface.co/Pi3141/alpaca-30B-ggml

**Comment by nasirus** [comment]
try do delete repository first :
sudo rm -r alpaca-30B-ggml
install git-lfs:
sudo apt-get install git-lfs
download it again :
git clone https://huggingface.co/Pi3141/alpaca-30B-ggml
