### ISSUE TITLE
Inaccuracy in README for Building from Source (Windows)

### ISSUE THREAD

**Issue by AnthonySchneider2000** [antimatter15/alpaca.cpp#123]
In this section, the following is stated: "Download the weights via any of the links in "Get started" above, and save the file as `ggml-alpaca-7b-q4.bin` in the main Alpaca directory."

Most would likely interpret "the main Alpaca directory" to be alpaca.cpp rather than Release, where the files are actually supposed to be downloaded.

**Comment by Mxbnt** [comment]
For what it's worth I tried this and it didn't work. 
I just download a different "ggml-alpaca-7b-q4.bin" and it now works properly with it copied directly in "alpaca.cpp" directory.

I downloaded the model from hugginface : https://huggingface.co/Sosaka/Alpaca-native-4bit-ggml/blob/main/ggml-alpaca-7b-q4.bin
