### ISSUE TITLE
Support for larger models

### ISSUE THREAD

**Issue by TemporalAgent7** [antimatter15/alpaca.cpp#13]
With the 7B weights, it hallucinates quite a bit; I'm wondering if we can get much better results with the larger sets (especially since it looks like there's plenty of room left over performance-wise on even mid-range machines).

It would be great if you could include the larger weight sets (pre-processed and ready to download / use).

Thanks!

**Comment by lofcz** [comment]
@andymatuschak thanks for sharing the tutorial! I wonder what are you getting as a response to the following query: `450000000000000000+1=?` (I'm getting nonsense, but `2+2` works fine), trying to confirm whether it's on my side.

**Comment by Bartvelp** [comment]
@andymatuschak Given that the retraining/patching takes quite some computing resources, could you be so kind as to upload the quantized 13B 8GiB model somewhere? Either over bittorrent or something else?

**Comment by lofcz** [comment]
@andymatuschak using your method I'm getting 401 unauthorized for ` https://huggingface.co/tloen/alpaca-lora-13b`. Can we substitute it with something? I've checked there is a similar repo hosted on GitHub with public access

**Comment by lofcz** [comment]
@andymatuschak I believe you must've also modify `convert-path-to-ggml.py` script, the `def get_n_parts(dim):` case `5120` to `1`, is this correct?

**Comment by HCBlackFox** [comment]
> I got 13B running. Was fairly straightforward. Some notes here: https://twitter.com/andy_matuschak/status/1636771172208771072

+1 Can you upload model pls.

**Comment by andymatuschak** [comment]
@lofcz 
> @andymatuschak thanks for sharing the tutorial! I wonder what are you getting as a response to the following query: `450000000000000000+1=?` (I'm getting nonsense, but `2+2` works fine), trying to confirm whether it's on my side.

Nope: 9223372036854775808. But that's pretty representative of a raw GPT3-ish model.

> I believe you must've also modified convert-path-to-ggml.py script, the def get_n_parts(dim): part, case 5120 to 1, is this correct?

Actually, I didn't—didn't seem to matter.

Not comfortable sharing the model myself.
