### ISSUE TITLE
Can I use Alpaca.CPP as a library? If so, how?

### ISSUE THREAD

**Issue by Sovenok-Hacker** [antimatter15/alpaca.cpp#134]
I am  making a simple application with Python and am trying to create a shared library (.so) for Alpaca.CPP to connect it to my Python code via CTypes.

Sorry, I am a teapot in C++.
If anyone can help me, please do.
Sorry for the disturbance.

**Comment by antimatter15** [comment]
Use https://github.com/ggerganov/llama.cpp
