### ISSUE TITLE
Am I dumb or is there no download link for the model anywhere?

### ISSUE THREAD

**Issue by gruevy** [antimatter15/alpaca.cpp#165]
I couldn't find a download link for the model, so I went to google and found a 'ggml-alpaca-7b-q4.bin' that someone put up on mega.nz, and it says

PS D:\stable diffusion\alpaca> ./chat
main: seed = 1679952842
llama_model_load: loading model from 'ggml-alpaca-7b-q4.bin' - please wait ...
llama_model_load: invalid model file 'ggml-alpaca-7b-q4.bin' (bad magic)
main: failed to load model from 'ggml-alpaca-7b-q4.bin'

Not sure if the model is bad, or the install. I installed from the alpaca-win.zip, and just put the 3 files into a new folder called alpaca. But first, I want to make sure I have a working model. Can I get a link?

**Comment by ShRajSh** [comment]
It's present in the test branch

**Comment by RiccaDS** [comment]
@ShRajSh I am dumb too, what is the test branch?

**Comment by gabriead** [comment]
> It's present in the test branch

Can you give a more specific hint?

**Comment by gruevy** [comment]
These ones worked for me. https://huggingface.co/Pi3141

**Comment by korewatori** [comment]
That sucks. Why is it legally murky?

**Comment by andersoncarli** [comment]
Try this:
curl -o ./models/ggml-alpaca-7b-q4.bin -C - https://ipfs.io/ipfs/QmUp1UGeQFDqJKvtjbSYPBiZZKRjLp8shVP9hT8ZB9Ynv1
