### ISSUE TITLE
Llama.cpp 30B runs with only 6GB of RAM now - update ?

### ISSUE THREAD

**Issue by magicmars35** [antimatter15/alpaca.cpp#182]
Llama.cpp 30B runs with only 6GB of RAM now : 

https://github.com/ggerganov/llama.cpp/pull/613

**Comment by anotherwanwanyi** [comment]
> It appears that this was just a misreading of how memory usage was being reported.

Take a look at jart's reply.
You still need 20GB of RAM.

https://news.ycombinator.com/item?id=35400066

**Comment by multimediaconverter** [comment]
I've just tried this new version of ggerganov's llama chat with the converted 7b ALPACA model. The result is very bad in my opinion, because on my laptop generation of tokens works 5 times slower. So, I strongly recommend to use the old fork from antimatter15.

**Comment by Openaicn** [comment]
please make clear 20GB RAM from GPU or motherboard?

**Comment by anotherwanwanyi** [comment]
@Openaicn Llama.cpp runs on the CPU.
