### ISSUE TITLE
doesn't work on Big Sur

### ISSUE THREAD

**Issue by indexofrefraction** [antimatter15/alpaca.cpp#194]
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/Anon/chat_mac (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

macOS Big Sur 11.7.5

**Comment by yujinqiu** [comment]
> dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE Referenced from: /Users/Anon/chat_mac (which was built for Mac OS X 12.0) Expected in: /usr/lib/libc++.1.dylib
> 
> macOS Big Sur 11.7.5

@indexofrefraction How do you fix  it?  I have the same issue, thanks.

**Comment by indexofrefraction** [comment]
@yujinqiu
i compiled it from source
I installed cmake using homebrew (https://brew.sh) and followed the instructions
note: it is important to start with ./chat and not with chat only!
