### ISSUE TITLE
Invite to add instructions and chat.cpp into llama.cpp

### ISSUE THREAD

**Issue by ggerganov** [antimatter15/alpaca.cpp#20]
@antimatter15 

Hey, I thought it would be useful both for [llama.cpp](https://github.com/ggerganov/llama.cpp) and [alpaca.cpp](https://github.com/ggerganov/alpaca.cpp) projects if we get these changes merged into the `llama.cpp` as well. We are working on some useful features, bug fixes and updates that will get integrated straight into alpaca.cpp if it is also available there.

I think to avoid too much efforts from your side, a simple PR with the `chat.cpp` program and a few words in the README how to run it should be enough. We will then pick it and integrate it better into the codebase. Can also reference the alpaca.cpp repo in the instructions for more detailed info.

I think this will reach even more people. But feel free to do as you find best!

Edit: here are instructions for the PR in case somebody from here decides to help out with the merge: https://github.com/ggerganov/llama.cpp/issues/240

**Comment by anzz1** [comment]
@ggerganov @antimatter15 
When you do integrate this to the parent repo please integrate the CI changes too for automatic releases as shown here https://github.com/anzz1/alpaca.cpp as having an option to not compile it yourself greatly improves accessibility for many people.

**Comment by ggerganov** [comment]
I just added everything necessary to the llama.cpp repo. Thanks
