### ISSUE TITLE
windows 10, fails to get to chat prompt

### ISSUE THREAD

**Issue by thistleknot** [antimatter15/alpaca.cpp#209]
(webgpt) H:\alpaca.cpp\Release>hello
'hello' is not recognized as an internal or external command,
operable program or batch file.

(webgpt) H:\alpaca.cpp\Release>chat.exe
main: seed = 1680832932
llama_model_load: loading model from 'ggml-alpaca-7b-q4.bin' - please wait ...
llama_model_load: ggml ctx size = 6065.34 MB
llama_model_load: memory_size =  2048.00 MB, n_mem = 65536
llama_model_load: loading model part 1/1 from 'ggml-alpaca-7b-q4.bin'
llama_model_load: .................................... done
llama_model_load: model size =  4017.27 MB / num tensors = 291

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | VSX = 0 |
main: interactive mode on.
sampling parameters: temp = 0.100000, top_k = 40, top_p = 0.950000, repeat_last_n = 64, repeat_penalty = 1.300000

**Comment by usamaehsan** [comment]
facing same issue, have you solved it?

**Comment by simsim314** [comment]
I guess you just need to wait, it takes time - but eventually, it finishes, I mean half an hour, go grab a coffee. Not sure that this is the case... but most probable one. It takes 10 minutes on my comp, with 13B, to get to the start of the chat.

P.S. This is was an important part: 

(webgpt) H:\alpaca.cpp\Release>hello
'hello' is not recognized as an internal or external command,
operable program or batch file.

**Comment by thistleknot** [comment]
The problem is it drops me back to a command prompt

**Comment by betolley** [comment]
What CPU do you use?  My I7 didn't support  AVX2  and this happened to me.  I changed the CMakelists to 
from
 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX2")
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /arch:AVX2")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:AVX2")

to 

 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX")
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /arch:AVX")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:AVX")

In a Virtual computer I even did
 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ")
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE})
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")

**Comment by thistleknot** [comment]
I7 3740qm I don't see avx2 just avx :/

**Comment by aka4el** [comment]
https://github.com/antimatter15/alpaca.cpp/issues/204#issue-1656024965      https://github.com/antimatter15/alpaca.cpp/issues/160#issue-1641136374 struggled with the same problem

**Comment by thistleknot** [comment]
That did it
![image](https://user-images.githubusercontent.com/5154106/230647168-7ce77eec-d047-4c4c-a25b-ef344785d982.png)


Curious, does anyone know how to get this to run on Cuda?  My Cuda capable GPU has 4GB of VRAM...

Could I in theory compile this with nvcc (I'm sure the code would have to be refactored).  I have yet to see someone post a CUDA enabled alpaca...  all I see are these CPU builds saying they will run on phones, yet they struggle to run on my I7 due to not having AVX2 I suppose.

**Comment by Red007Master** [comment]
> What CPU do you use? My I7 didn't support AVX2 and this happened to me. I changed the CMakelists to from set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX2") set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /arch:AVX2") set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:AVX2")
> 
> to
> 
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX") set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /arch:AVX") set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:AVX")
> 
> In a Virtual computer I even did set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ") set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}) set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")

Thanks, worked for me, indeed my CPU did not support AVX2.
