### ISSUE TITLE
CUDA support?

### ISSUE THREAD

**Issue by thistleknot** [antimatter15/alpaca.cpp#211]
Will this ever be enabled for Cuda inference?

**Comment by aka4el** [comment]
You can try this solution from the next branch (I successfully switched to it, but I have 12 GB of video memory)  https://github.com/oobabooga/text-generation-webui#readme
Scroll the page to the points - **Installation-One-Click Installers**-oobabooga-windows.zip
Just download the zip and follow the instructions, everything will go in auto mode. With a small amount of video memory, there are options to use hybrid modes using the CPU, RAM, disk cache.
You can also read about small video memory and here - https://github.com/oobabooga/text-generation-webui/wiki/Low-VRAM-guide

**Comment by thistleknot** [comment]
This is cool.  I read about quantizing the model down using some other
methods...  I thought I'd try my hand

https://github.com/juncongmoo/pyllama

**Comment by thistleknot** [comment]
this isreally cool, thanks for the tip!
