### ISSUE TITLE
Magnet link not working

### ISSUE THREAD

**Issue by AlpinDale** [antimatter15/alpaca.cpp#33]
Hi. Magnet link appears to be broken, metadata doesn't download. Please update the `README.md` file to include a `.torrent` file. You can use services such as [catbox.moe](https://catbox.moe) to host the torrent file. Thanks.

**Comment by prettydeep** [comment]
7B link is good on my end. But the 13B magnet link fails to load metadata.

**Comment by antimatter15** [comment]
fixed

**Comment by clevebre** [comment]
magnet:?xt=urn:btih:053B3D54D2E77FF020EBDDF51DAD681F2A651071&tr=udp%3A%2F%2Ftracker.bitsearch.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker2.dler.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fwww.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.breizh.pm%3A6969%2Fannounce&dn=%5BBitsearch.to%5D+ggml-alpaca-13b-q4.bin
