### ISSUE TITLE
Bias of ggml-alpaca-7b-q4.bin

### ISSUE THREAD

**Issue by jellomaster** [antimatter15/alpaca.cpp#34]
Start by asking: Is Hillary Clinton good?
Follow with: Is Donald Trump good?
and after that: Is Joe Biden good?

**Comment by fastrocket** [comment]
Gpt-4 has fixed some of the anti-Trump bias. You can now ask for articles on why Trump and MAGA are good directly. So it's doable.

**Comment by anzz1** [comment]
> Gpt-4 has fixed some of the anti-Trump bias. You can now ask for articles on why Trump and MAGA are good directly. So it's doable.

You really think that is "fixing" it? You missed the point entirely. Please read the comment again and apply some thought.
