### ISSUE TITLE
CMake Error at CMakeLists.txt:2 (project):   Running     'nmake' '-?'    failed with:     The system cannot find the file specified

### ISSUE THREAD

**Issue by athenicantiableism** [antimatter15/alpaca.cpp#35]
I get the following error on running cmake .
`CMake Error at CMakeLists.txt:2 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
PS C:\Users\[...]\OneDrive\Documents\GitHub\alpaca.cpp>`

**Comment by tprototype** [comment]
[Windows] same error

**Comment by HCBlackFox** [comment]
https://stackoverflow.com/questions/69338088/error-while-configuring-cmake-project-running-nmake-failed 

The solution was to append -G "MinGW Makefiles" to cmake -S . -B Build command. This worked for me, you can also try to use another variants. Just write a "cmake -G" and see full list of posible variants.  

Also, there is a release for now, and you dont anymore need to buld project by yourself.

**Comment by adamjames** [comment]
I installed mingw to get mingw-make.exe, and then told cmake to use the MinGW Makefiles generator:


```
PS C:\Tools\alpaca\alpaca.cpp> scoop install mingw
Installing 'mingw' (12.2.0-rt_v10-rev1) [64bit] from main bucket
x86_64-12.2.0-release-posix-seh-rt_v10-rev1.7z (67.7 MB) [====================================================] 100%
Checking hash of x86_64-12.2.0-release-posix-seh-rt_v10-rev1.7z ... ok.
Extracting x86_64-12.2.0-release-posix-seh-rt_v10-rev1.7z ... done.
Linking ~\scoop\apps\mingw\current => ~\scoop\apps\mingw\12.2.0-rt_v10-rev1
Running post_install script...
'mingw' (12.2.0-rt_v10-rev1) was installed successfully!

PS C:\Tools\alpaca\alpaca.cpp> cmake . -G "MinGW Makefiles"
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/Adam/scoop/apps/mingw/current/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/Adam/scoop/apps/mingw/current/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- x86 detected
-- Configuring done (2.1s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Tools/alpaca/alpaca.cpp
PS C:\Tools\alpaca\alpaca.cpp>
```

**Comment by mundahl** [comment]
adamjames's step helped me! if you don't have scoop yet installed, like me, call the following in Windows PowerShell

`iwr -useb get.scoop.sh | iex`

Such as:

`PS C:\repo\AI\llm\alpaca\antimatter15\alpaca.cpp> iwr -useb get.scoop.sh | iex
Initializing...
Downloading ...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.`

**Comment by hjude** [comment]
In this case for installation you should use it in Developer Command Prompt window (Developer Command Prompt for VS 2022), you can find it in  C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2022\Visual Studio Tools. 
1. Remove old alpaca.cpp folder 
2. Reinstall using Developer Command Prompt for VS 2022

**Comment by athenicantiableism** [comment]
It seems I didn't have Visual Studio installed. I was just following your instructions and they didn't mention that requirement. However, many thanks! It seems the code works after installing VS (Visual Studio).

**Comment by arun-iitg025** [comment]
> I get the following error on running cmake . `CMake Error at CMakeLists.txt:2 (project): Running
> 
> 'nmake' '-?'
> 
> failed with:
> 
> The system cannot find the file specified
> 
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage -- Configuring incomplete, errors occurred! PS C:\Users[...]\OneDrive\Documents\GitHub\alpaca.cpp>`

How did you fix the error.
please reply !

**Comment by parabath** [comment]
I didn't fixed error

**Comment by athenicantiableism** [comment]
> > I get the following error on running cmake . `CMake Error at CMakeLists.txt:2 (project): Running
> > 'nmake' '-?'
> How did you fix the error. please reply !

It's already in the thread. That's why it says "[athenicantiableism](https://github.com/athenicantiableism) closed this as [completed](https://github.com/antimatter15/alpaca.cpp/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [on Mar 21, 2023](https://github.com/antimatter15/alpaca.cpp/issues/35#event-8800574383)," above. I had to install Visual Studio.
