### ISSUE TITLE
Can someone with full 13b model connect to the torrent?

### ISSUE THREAD

**Issue by HCBlackFox** [antimatter15/alpaca.cpp#37]
We stucked at 92.7% without any seeds.

**Comment by artegoser** [comment]
This is ridiculous.

**Comment by BadisG** [comment]
Yeah same I'm stuck at 92.7%

**Comment by kaz9112** [comment]
anyone knows how to merge the llama 13b with the lora wiehgt? maybe we can do it our own, unless it needs some heavy gpu power...

**Comment by HCBlackFox** [comment]
> anyone knows how to merge the llama 13b with the lora wiehgt? maybe we can do it our own, unless it needs some heavy gpu power...

https://github.com/tloen/alpaca-lora all described here

**Comment by GeorgesAlkhouri** [comment]
https://twitter.com/sueringer_1a/status/1637064548707336192 :smile:

**Comment by HCBlackFox** [comment]
We have seeder!

**Comment by PriNova** [comment]
Yes, no missing parts

**Comment by kaz9112** [comment]
come on people, don't just quit once you're done, jesus...

**Comment by HCBlackFox** [comment]
> come on people, don't just quit once you're done, jesus...

Lol 99.9%

**Comment by BadisG** [comment]
It's a troll at this point, I'm stuck at 99.9% lmao

**Comment by artegoser** [comment]
cringe

**Comment by ymcui** [comment]
I am stucked at 99.95% but it seems that it can be loaded anyway. :) 
<img width="1374" alt="13b-test" src="https://user-images.githubusercontent.com/16095339/226108716-b339c27c-2149-4c36-8922-96f69bedc322.png">

**Comment by artegoser** [comment]
how

**Comment by HCBlackFox** [comment]
> I am stucked at 99.95% but it seems that it can be loaded anyway. :) <img alt="13b-test" width="1374" src="https://user-images.githubusercontent.com/16095339/226108716-b339c27c-2149-4c36-8922-96f69bedc322.png">

For me its produce an error.

**Comment by BadisG** [comment]
> I am stucked at 99.95% but it seems that it can be loaded anyway. :) <img alt="13b-test" width="1374" src="https://user-images.githubusercontent.com/16095339/226108716-b339c27c-2149-4c36-8922-96f69bedc322.png">

I have this error personally 
![image](https://user-images.githubusercontent.com/110173477/226109241-43dbb0d5-e36d-4bda-b436-1ea68a6f22dc.png)

**Comment by HCBlackFox** [comment]
> I am stucked at 99.95% but it seems that it can be loaded anyway. :) <img alt="13b-test" width="1374" src="https://user-images.githubusercontent.com/16095339/226108716-b339c27c-2149-4c36-8922-96f69bedc322.png">

Can u provide a hash of your file pls?

**Comment by PriNova** [comment]
I guess it depends if the missing parts will be filed with zeros from the torrent downloader.
If so, then it could be possible loaded with missing (zero) weights.

**Comment by ymcui** [comment]
> > I am stucked at 99.95% but it seems that it can be loaded anyway. :) <img alt="13b-test" width="1374" src="https://user-images.githubusercontent.com/16095339/226108716-b339c27c-2149-4c36-8922-96f69bedc322.png">
> 
> Can u provide a hash of your file pls?

```
(base) % md5 ggml-alpaca-13b-q4.bin
MD5 (ggml-alpaca-13b-q4.bin) = 1c62f0f721faf3662673957bfffd5139
(base) % openssl sha256 ggml-alpaca-13b-q4.bin
SHA256(ggml-alpaca-13b-q4.bin)= ff907f37a21e70f06a15bd83c39425257869683c44012827c9fb58e2cc954b66
```

**Comment by BadisG** [comment]
> 

![image](https://user-images.githubusercontent.com/110173477/226109685-08a49add-79f8-46f4-83b1-d870cd86e19f.png)
I have exactly the same hash as you.

Did you change the chat.ccp code? On your terminal it loads a 1/1 and for us it's a 1/2.

**Comment by ymcui** [comment]
> ![image](https://user-images.githubusercontent.com/110173477/226109685-08a49add-79f8-46f4-83b1-d870cd86e19f.png) I have exactly the same hash as you.
> 
> Did you change the chat.ccp code? On your terminal it loads a 1/1 and for us it's a 1/2.

No. I did not change anything. Just pull the latest code and `make chat` and run `/chat -m ggml-alpaca-13b-q4.bin`

**Comment by BadisG** [comment]
> > ![image](https://user-images.githubusercontent.com/110173477/226109685-08a49add-79f8-46f4-83b1-d870cd86e19f.png) I have exactly the same hash as you.
> > Did you change the chat.ccp code? On your terminal it loads a 1/1 and for us it's a 1/2.
> 
> No. I did not change anything. Just pull the latest code and `make chat` and run `./chat -m ggml-alpaca-13b-q4.bin`

Oh I got it, I had to delete the chat file and make a new one with make chat.

Everyone, do a git pull, erase the chat file if you have one already and recompile it again with a "make chat"

It worked for me! Thanks [ymcui](https://github.com/ymcui) !

**Comment by ymcui** [comment]
> > > ![image](https://user-images.githubusercontent.com/110173477/226109685-08a49add-79f8-46f4-83b1-d870cd86e19f.png) I have exactly the same hash as you.
> > > Did you change the chat.ccp code? On your terminal it loads a 1/1 and for us it's a 1/2.
> > 
> > 
> > No. I did not change anything. Just pull the latest code and `make chat` and run `./chat -m ggml-alpaca-13b-q4.bin`
> 
> Oh I got it, I had to delete the chat file and make a new one with make chat.
> 
> Everyone, do a git pull, erase the chat file if you have one already and compile it again with a "make chat"
> 
> It worked for me! Thanks [ymcui](https://github.com/ymcui) !

Glad to hear! It seems that the code has been updated after the release of 13B model, so we should compile with the latest code and use a new `./chat` binary file. 🎉🎉🎉

**Comment by Kronos256** [comment]
I am stuck at 99.9% if someone kind enough can seed it please ...

**Comment by BadisG** [comment]
> I am stuck at 99.9% if someone kind enough can seed it please ...

You can use it anyway, it works surprisignly

**Comment by HCBlackFox** [comment]
> > > > ![image](https://user-images.githubusercontent.com/110173477/226109685-08a49add-79f8-46f4-83b1-d870cd86e19f.png) I have exactly the same hash as you.
> > > > Did you change the chat.ccp code? On your terminal it loads a 1/1 and for us it's a 1/2.
> > > 
> > > 
> > > No. I did not change anything. Just pull the latest code and `make chat` and run `./chat -m ggml-alpaca-13b-q4.bin`
> > 
> > 
> > Oh I got it, I had to delete the chat file and make a new one with make chat.
> > Everyone, do a git pull, erase the chat file if you have one already and compile it again with a "make chat"
> > It worked for me! Thanks [ymcui](https://github.com/ymcui) !
> 
> Glad to hear! It seems that the code has been updated after the release of 13B model, so we should compile with the latest code and use a new `./chat` binary file. 🎉🎉🎉

+1 works for me, thank you <3

**Comment by artegoser** [comment]
yeeeessss, it done

**Comment by HCBlackFox** [comment]
https://github.com/ymcui/alpaca.cpp

https://pan.baidu.com/s/1zIyjFb6c7biq7Wb2PqPkWw?pwd=2mnu

**Comment by justinh-rahb** [comment]
I'm seeding it now on symetric gig fiber.
