### ISSUE TITLE
can it run on gpu?

### ISSUE THREAD

**Issue by pkellyuk** [antimatter15/alpaca.cpp#39]
seems to use cpu only?

**Comment by HCBlackFox** [comment]
Yes, its only for cpu.

**Comment by nenkoru** [comment]
As stated in #62 there is a project called [alpaca-lora](https://github.com/tloen/alpaca-lora) that does able to run on a GPU as well as MPS. 
For me(M1 PRO) running on MPS was much-much slower than running this wrapper targetting CPU.
