### ISSUE TITLE
Does thread count make a difference? Defaults to 4/12 for my comp.

### ISSUE THREAD

**Issue by imesha10** [antimatter15/alpaca.cpp#41]
I changed n_threads to 10 from the min function it was before, (my computer supports 12, before changes it defaulted to 4 threads). Then I compiled it. I do see those threads now being utilized. It does seem a bit faster idk.

The original code:
https://github.com/antimatter15/alpaca.cpp/blob/4a524c51ba42254fdae63abcf26d38f64dd4fc28/utils.h#L15-L17

**Comment by EeveeTea** [comment]
The default is a safe average and should probably not be changed. You can change the number of threads with the -t argument: `./chat -t 10`

Remember to check `./chat -h` for a full list of possible arguments to tweak the model and outputs.

**Comment by imesha10** [comment]
Oh wow ok thanks, i didn't know that option was there. I'm going to close this issue, however if you think other people may want to see this ig reopen the issue or add it to the readme. Thanks.
