### ISSUE TITLE
How to load the 13B model?

### ISSUE THREAD

**Issue by afgonczol** [antimatter15/alpaca.cpp#43]
The magnet link for the 13B model is working now and I have it downloaded, but how can I make the chat program load that model instead of the 7B model?

**Comment by RiverIsAMovingBodyOfWater** [comment]
Upload files and i would tell you how to use 13B
I am still stuck at 99%

**Comment by RiverIsAMovingBodyOfWater** [comment]
> The magnet link for the 13B model is working now and I have it downloaded, but how can I make the chat program load that model instead of the 7B model?

**Comment by RiverIsAMovingBodyOfWater** [comment]
Upload files and i would tell you how to use 13B
I am still stuck at 99%

**Comment by RiverIsAMovingBodyOfWater** [comment]
Just rename 13B model to ggml-alpaca-7b-q4.bin and it should work

**Comment by artegoser** [comment]
`./chat -m ggml-alpaca-13b-q4.bin` in readme

**Comment by afgonczol** [comment]
I spoke too soon. I'm also stuck at 99.9%.

**Comment by afgonczol** [comment]
Even though the torrent says 99.9% and downloading about 1kb/s I noticed that the file size on my computer wasn't changing at all. I decided to just load it anyway and it seems to be working fine.
