### ISSUE TITLE
No \release\chat.exe found?

### ISSUE THREAD

**Issue by Crimsonfart** [antimatter15/alpaca.cpp#48]
Hello
I get the following error:
Microsoft Windows [Version 10.0.22621.1413]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\basil\Documents\Neuer Ordner\alpaca.cpp>cmake .
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.35.32215.0
-- The CXX compiler identification is MSVC 19.35.32215.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- x86 detected
-- Configuring done (8.8s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Users/basil/Documents/Neuer Ordner/alpaca.cpp

C:\Users\basil\Documents\Neuer Ordner\alpaca.cpp>.\Release\chat.exe
Das System kann den angegebenen Pfad nicht finden. (The system can not find the path specified.)

C:\Users\basil\Documents\Neuer Ordner\alpaca.cpp>

**Comment by HCBlackFox** [comment]
You skiped command: ```shell
cmake --build . --config Release
```
