### ISSUE TITLE
Add link to 13b model in readme.

### ISSUE THREAD

**Issue by HCBlackFox** [antimatter15/alpaca.cpp#50]
I uploaded a 13b model to anon files: https://anonfiles.com/9bB0s8faz4/ggml_alpaca_13b_q4_bin

**Comment by myeolinmalchi** [comment]
This link doesn't work.

**Comment by coelhobugado** [comment]
> Carreguei um modelo 13b para arquivos anon: https://anonfiles.com/9bB0s8faz4/ggml_alpaca_13b_q4_bin

does it support replying in other languages? if not what differential does this have from 13b to the other?

**Comment by loretoparisi** [comment]
So download would be `curl -O ggml_alpaca_13b_q4_bin https://anonfiles.com/9bB0s8faz4/ggml_alpaca_13b_q4_bin`
