### ISSUE TITLE
 Element <EnableEnhan cedInstructionSet> has an invalid value of "AdvancedVectorExtensions2".

### ISSUE THREAD

**Issue by MCH223** [antimatter15/alpaca.cpp#53]
when I run cmake --build . --confing Release I git this ` cmake --build . --config Release
Microsoft (R) Build Engine version 12.0.21005.1
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/CHATGPT/alpaca.cpp/CMakeLists.txt
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(341,5): error : Element <EnableEnhan
cedInstructionSet> has an invalid value of "AdvancedVectorExtensions2". [C:\CHATGPT\alpaca.cpp\ggml.vcxproj] `

**Comment by ndrefg** [comment]
Try a release instead of compiling :>

**Comment by MCH223** [comment]
> Try a release instead of compiling :>

how do I do that?

**Comment by antimatter15** [comment]
> > Try a release instead of compiling :>
> 
> how do I do that?

https://github.com/antimatter15/alpaca.cpp/releases/tag/99f3908
