### ISSUE TITLE
Unexpected response for meeting summary

### ISSUE THREAD

**Issue by testplop** [antimatter15/alpaca.cpp#64]
Thanks for your amazing work.

I try to summarize this note, but I get a endless loop of unexpected response. Can you help ?

https://platform.openai.com/examples/default-notes-summary

<img width="1440" alt="Screenshot 2023-03-19 at 09 52 01" src="https://user-images.githubusercontent.com/74246611/226164153-a6915460-bc93-43eb-b36c-7f64dad8f0be.png">

**Comment by nenkoru** [comment]
Make sure to use '\' as a break of the line as stated at the README.
\n persumably treated in a bad way by a model:

> == Running in chat mode. ==
>  - Press Ctrl+C to interject at any time.
>  - Press Return to return control to LLaMA.
>  - If you want to submit another line, end your input in '\'

**Comment by testplop** [comment]
<img width="1199" alt="Screenshot 2023-03-19 at 12 14 32" src="https://user-images.githubusercontent.com/74246611/226171643-52991211-0da5-42fb-b8b8-0506cdc6b608.png">

**Comment by testplop** [comment]
<img width="524" alt="Screenshot 2023-03-19 at 12 16 33" src="https://user-images.githubusercontent.com/74246611/226171710-fa92c370-78bb-4d98-ac46-2976a3705874.png">
