### ISSUE TITLE
Not an issue. How to add our own trainings on top of supplied model and tune it?

### ISSUE THREAD

**Issue by Mahabali** [antimatter15/alpaca.cpp#69]
Sorry i am noob to the whole ML/AI thing. any pointers would help

**Comment by salmon-coder** [comment]
Playing around with the prompting strategy is probably the first thing to try

**Comment by antimatter15** [comment]
alpaca.cpp is mostly meant to be beginner friendly, if you want to dive deeper into this stuff you should probably turn to more advanced software like [llama.cpp](https://github.com/ggerganov/llama.cpp) or [alpaca-lora](https://github.com/tloen/alpaca-lora)
