### ISSUE TITLE
Example about custom training

### ISSUE THREAD

**Issue by paulocoutinhox** [antimatter15/alpaca.cpp#72]
Hi,

How can i use 7B (or other) with a mine custom dataset to make questions about my dataset?

Do you have an example?

Thanks.

**Comment by antimatter15** [comment]
alpaca.cpp is mostly meant to be beginner friendly, if you want to dive deeper into this stuff you should probably turn to more advanced software like [llama.cpp](https://github.com/ggerganov/llama.cpp) or [alpaca-lora](https://github.com/tloen/alpaca-lora)
