### ISSUE TITLE
ipfs address for ggml-alpaca-13b-q4.bin

### ISSUE THREAD

**Issue by bombless** [antimatter15/alpaca.cpp#77]
New Bing tells me it's `QmZxQFgkP5zrEa3KsVwY8cM9hNtHdC6oXg7iRnqUuL3fDv` but I cannot download it.
Is this the right value?

**Comment by tempteam** [comment]
I downloaded the model from this link without any problems


`magnet:?xt=urn:btih:053b3d54d2e77ff020ebddf51dad681f2a651071&dn=ggml-alpaca-13b-q4.bin&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce`

**Comment by tempteam** [comment]
> New Bing tells me it's `QmZxQFgkP5zrEa3KsVwY8cM9hNtHdC6oXg7iRnqUuL3fDv` but I cannot download it. Is this the right value?


I downloaded the model from this link without any problems

magnet:?xt=urn:btih:053b3d54d2e77ff020ebddf51dad681f2a651071&dn=ggml-alpaca-13b-q4.bin&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce

**Comment by GrahamboJangles** [comment]
Where's the 30B tho

**Comment by bmwiedemann** [comment]
alpaca/models/13B/ggml-model-q4_0.bin is `QmaASKxskxikdkMsq9Nsoj1gKRVucPYp7SEuzQDZsnXvJc`

and 7B is probably `QmQ1bf2BTnYxq73MFJWu1B7bQ2UD6qG7D7YDCxhTndVkPC`

**Comment by bmwiedemann** [comment]
extended the collection:
```
QmefpLkj1Pv6bPQEwC9dBV96MTvwGMbnHEGjCmeSdKdLYk alpaca.30B
QmaASKxskxikdkMsq9Nsoj1gKRVucPYp7SEuzQDZsnXvJc alpaca.13B
QmQ1bf2BTnYxq73MFJWu1B7bQ2UD6qG7D7YDCxhTndVkPC alpaca.7B
```
