### ISSUE TITLE
It answers weird symbols

### ISSUE THREAD

**Issue by lyfxyz12** [antimatter15/alpaca.cpp#78]
![image](https://user-images.githubusercontent.com/41572256/226229811-5269acef-dc6e-40d2-8fcc-bd4287d3f4d5.png)

**Comment by itugs** [comment]
same problem here.

**Comment by shahzadgamedev** [comment]
same problem please Fix This !

**Comment by Disa-Kizonda** [comment]
true

![image](https://user-images.githubusercontent.com/53359732/226299014-cd1eba94-99f2-4e5b-b953-fc574d930137.png)

**Comment by simonUU** [comment]
The model.bin should have 4GB size. Possibly it is corrupt. Maybe try to re-download the weights.

**Comment by itugs** [comment]
I fixed this by downloading correct model.
