### ISSUE TITLE
Fine tune

### ISSUE THREAD

**Issue by dinosaurtirex** [antimatter15/alpaca.cpp#82]
Hello! Is it possible to fine tune current weight on my own dataset? Anyone tried?

**Comment by antimatter15** [comment]
alpaca.cpp is mostly meant to be beginner friendly, if you want to dive deeper into this stuff you should probably turn to more advanced software like [llama.cpp](https://github.com/ggerganov/llama.cpp) or [alpaca-lora](https://github.com/tloen/alpaca-lora)
