### ISSUE TITLE
Slow performance in Google Colab and no GPU acceleration to make it faster.

### ISSUE THREAD

**Issue by ikmalsaid** [antimatter15/alpaca.cpp#91]
Hi! I am experiencing slow performance when displaying output from my prompts. I have followed the steps that you have wrote so is there any way to make the display of output faster? I also do not see it using the GPU (Nvidia Tesla T4).

**Comment by kaz9112** [comment]
> 

my guy, this is cpu only...

**Comment by ikmalsaid** [comment]
Ahh yes. Sorry about that. Closing case 3...2...1...0
